/**
 * VALORHIVE - Tournament Recap Service (v3.48.0)
 * 
 * Generates tournament summaries and recaps.
 * Part of the Completion & Trust Layer.
 * 
 * Key Features:
 * - Auto-generated tournament recaps
 * - Highlight extraction
 * - Final standings summary
 * - Shareable summary cards
 */

import { db } from '@/lib/db';
import { CompletionAction, SportType } from '@prisma/client';

// ============================================
// TYPES
// ============================================

interface RecapResult {
  success: boolean;
  recapId?: string;
  error?: string;
}

// Typed interfaces for match data
interface MatchPlayer {
  id: string;
  firstName: string;
  lastName: string;
  hiddenElo?: number;
}

interface MatchTeam {
  id: string;
  name: string;
  teamElo?: number;
}

interface MatchData {
  id: string;
  playerAId?: string;
  playerBId?: string;
  teamAId?: string;
  teamBId?: string;
  winnerId?: string;
  winnerTeamId?: string;
  scoreA?: number;
  scoreB?: number;
  playerA?: MatchPlayer | null;
  playerB?: MatchPlayer | null;
  teamA?: MatchTeam | null;
  teamB?: MatchTeam | null;
}

interface TournamentResultData {
  rank: number;
  userId: string;
  bonusPoints?: number;
  user: {
    id: string;
    firstName: string;
    lastName: string;
  };
}

interface TournamentWithRelations {
  id: string;
  name: string;
  sport: string;
  format: string;
  location?: string | null;
  results: TournamentResultData[];
  matches: MatchData[];
  registrations?: { userId: string }[];
  teamRegistrations?: { id: string }[];
}

interface LongestMatchInfo {
  matchId: string;
  playerAName: string;
  playerBName: string;
  scoreA: number | null;
  scoreB: number | null;
  margin: number;
}

interface HighestScoreInfo {
  matchId: string;
  playerAName: string;
  playerBName: string;
  scoreA: number | null;
  scoreB: number | null;
  total: number;
}

interface StandingEntry {
  rank: number;
  playerId: string;
  playerName: string;
  bonusPoints?: number;
}

interface RecapData {
  title: string;
  summary: string;
  highlights: string[];
  totalMatches: number;
  totalUpsets: number;
  longestMatch?: LongestMatchInfo;
  highestScore?: HighestScoreInfo;
  mvpPlayerId?: string;
  topScorerId?: string;
  standings: StandingEntry[];
}

// ============================================
// RECAP GENERATION
// ============================================

/**
 * Generate a tournament recap
 */
export async function generateTournamentRecap(
  tournamentId: string
): Promise<RecapResult> {
  try {
    // Check if recap already exists
    const existing = await db.tournamentRecap.findUnique({
      where: { tournamentId }
    });

    if (existing) {
      return {
        success: true,
        recapId: existing.id
      };
    }

    // Get tournament with all data
    const tournament = await db.tournament.findUnique({
      where: { id: tournamentId },
      include: {
        snapshot: true,
        results: {
          include: {
            user: { select: { id: true, firstName: true, lastName: true } }
          }
        },
        matches: {
          include: {
            playerA: { select: { id: true, firstName: true, lastName: true, hiddenElo: true } },
            playerB: { select: { id: true, firstName: true, lastName: true, hiddenElo: true } },
            teamA: { select: { id: true, name: true, teamElo: true } },
            teamB: { select: { id: true, name: true, teamElo: true } }
          }
        },
        registrations: { select: { userId: true } }
      }
    });

    if (!tournament) {
      return { success: false, error: 'Tournament not found' };
    }

    // Build recap data
    const recapData = await buildRecapData(tournament);

    // Create recap
    const recap = await db.tournamentRecap.create({
      data: {
        tournamentId,
        sport: tournament.sport,
        title: recapData.title,
        summary: recapData.summary,
        highlights: JSON.stringify(recapData.highlights),
        totalMatches: recapData.totalMatches,
        totalUpsets: recapData.totalUpsets,
        longestMatch: recapData.longestMatch ? JSON.stringify(recapData.longestMatch) : null,
        highestScore: recapData.highestScore ? JSON.stringify(recapData.highestScore) : null,
        mvpPlayerId: recapData.mvpPlayerId,
        topScorerId: recapData.topScorerId,
        standings: JSON.stringify(recapData.standings),
        isAutoGenerated: true,
        generatedAt: new Date(),
        isPublic: true
      }
    });

    // Log action
    await logRecapAction(tournamentId, CompletionAction.RECAP_GENERATED, {
      recapId: recap.id,
      highlightCount: recapData.highlights.length
    });

    return {
      success: true,
      recapId: recap.id
    };

  } catch (error) {
    console.error('Error generating tournament recap:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

// ============================================
// RECAP DATA BUILDING
// ============================================

/**
 * Build recap data from tournament
 */
async function buildRecapData(tournament: TournamentWithRelations): Promise<RecapData> {
  const isTeamFormat = tournament.format === 'DOUBLES' || tournament.format === 'TEAM';

  // Get winner info
  const champion = tournament.results.find((r) => r.rank === 1);
  const runnerUp = tournament.results.find((r) => r.rank === 2);
  const thirdPlace = tournament.results.find((r) => r.rank === 3);

  // Build title
  const winnerName = champion
    ? `${champion.user.firstName} ${champion.user.lastName}`
    : 'Unknown';
  const title = `${tournament.name} - ${winnerName} Wins!`;

  // Build summary
  const participantCount = isTeamFormat
    ? tournament.teamRegistrations?.length || 0
    : tournament.registrations?.length || 0;
  
  const summary = `${tournament.name} concluded with ${participantCount} participants. ` +
    `${winnerName} emerged victorious ${runnerUp ? `defeating ${runnerUp.user.firstName} ${runnerUp.user.lastName} in the finals` : ''}. ` +
    `The tournament featured ${tournament.matches?.length || 0} matches over the course of the event.`;

  // Extract highlights
  const highlights = extractHighlights(tournament);

  // Calculate upsets
  const totalUpsets = calculateUpsets(tournament);

  // Find longest match
  const longestMatch = findLongestMatch(tournament.matches);

  // Find highest scoring match
  const highestScore = findHighestScore(tournament.matches);

  // Determine MVP (most wins)
  const mvpPlayerId = await determineMVP(tournament);

  // Determine top scorer
  const topScorerId = await determineTopScorer(tournament);

  // Get standings
  const standings = tournament.results.map((r) => ({
    rank: r.rank,
    playerId: r.userId,
    playerName: `${r.user.firstName} ${r.user.lastName}`,
    bonusPoints: r.bonusPoints
  })).sort((a, b) => a.rank - b.rank);

  return {
    title,
    summary,
    highlights,
    totalMatches: tournament.matches?.length || 0,
    totalUpsets,
    longestMatch,
    highestScore,
    mvpPlayerId,
    topScorerId,
    standings
  };
}

/**
 * Extract highlights from tournament
 */
function extractHighlights(tournament: TournamentWithRelations): string[] {
  const highlights: string[] = [];
  const isTeamFormat = tournament.format === 'DOUBLES' || tournament.format === 'TEAM';

  // Winner highlight
  const champion = tournament.results.find((r) => r.rank === 1);
  if (champion) {
    highlights.push(`🏆 Champion: ${champion.user.firstName} ${champion.user.lastName}`);
  }

  // Runner-up highlight
  const runnerUp = tournament.results.find((r) => r.rank === 2);
  if (runnerUp) {
    highlights.push(`🥈 Runner-up: ${runnerUp.user.firstName} ${runnerUp.user.lastName}`);
  }

  // Third place highlight
  const thirdPlace = tournament.results.find((r) => r.rank === 3);
  if (thirdPlace) {
    highlights.push(`🥉 Third Place: ${thirdPlace.user.firstName} ${thirdPlace.user.lastName}`);
  }

  // Close matches highlight
  const closeMatches = tournament.matches?.filter((m) => {
    const diff = Math.abs((m.scoreA || 0) - (m.scoreB || 0));
    return diff === 1;
  }).length || 0;

  if (closeMatches > 0) {
    highlights.push(`🎯 ${closeMatches} matches decided by 1 point`);
  }

  // Highest score highlight
  const highestScoreMatch = findHighestScore(tournament.matches);
  if (highestScoreMatch) {
    highlights.push(`📊 Highest score: ${highestScoreMatch.scoreA}-${highestScoreMatch.scoreB}`);
  }

  // Participation highlight
  const participantCount = isTeamFormat
    ? tournament.teamRegistrations?.length || 0
    : tournament.registrations?.length || 0;

  highlights.push(`👥 ${participantCount} participants`);

  return highlights;
}

/**
 * Calculate number of upsets
 */
function calculateUpsets(tournament: TournamentWithRelations): number {
  let upsets = 0;
  const isTeamFormat = tournament.format === 'DOUBLES' || tournament.format === 'TEAM';

  for (const match of tournament.matches || []) {
    if (!match.winnerId && !match.winnerTeamId) continue;

    if (isTeamFormat) {
      const winnerElo = match.winnerTeamId === match.teamAId 
        ? (match.teamA?.teamElo || 1000)
        : (match.teamB?.teamElo || 1000);
      const loserElo = match.winnerTeamId === match.teamAId 
        ? (match.teamB?.teamElo || 1000)
        : (match.teamA?.teamElo || 1000);
      
      if (winnerElo < loserElo - 50) upsets++;
    } else {
      const winnerElo = match.winnerId === match.playerAId 
        ? (match.playerA?.hiddenElo || 1500)
        : (match.playerB?.hiddenElo || 1500);
      const loserElo = match.winnerId === match.playerAId 
        ? (match.playerB?.hiddenElo || 1500)
        : (match.playerA?.hiddenElo || 1500);
      
      if (winnerElo < loserElo - 50) upsets++;
    }
  }

  return upsets;
}

/**
 * Find the longest/closest match
 */
function findLongestMatch(matches: MatchData[]): LongestMatchInfo | null {
  if (!matches || matches.length === 0) return null;

  // For now, find the match with the smallest margin
  let closest = null;
  let smallestMargin = Infinity;

  for (const match of matches) {
    const margin = Math.abs((match.scoreA || 0) - (match.scoreB || 0));
    if (margin > 0 && margin < smallestMargin) {
      smallestMargin = margin;
      closest = match;
    }
  }

  if (!closest) return null;

  return {
    matchId: closest.id,
    playerAName: closest.playerA 
      ? `${closest.playerA.firstName} ${closest.playerA.lastName}` 
      : closest.teamA?.name,
    playerBName: closest.playerB 
      ? `${closest.playerB.firstName} ${closest.playerB.lastName}` 
      : closest.teamB?.name,
    scoreA: closest.scoreA,
    scoreB: closest.scoreB,
    margin: smallestMargin
  };
}

/**
 * Find highest scoring match
 */
function findHighestScore(matches: MatchData[]): HighestScoreInfo | null {
  if (!matches || matches.length === 0) return null;

  let highest = null;
  let maxTotal = 0;

  for (const match of matches) {
    const total = (match.scoreA || 0) + (match.scoreB || 0);
    if (total > maxTotal) {
      maxTotal = total;
      highest = match;
    }
  }

  if (!highest) return null;

  return {
    matchId: highest.id,
    playerAName: highest.playerA 
      ? `${highest.playerA.firstName} ${highest.playerA.lastName}` 
      : highest.teamA?.name,
    playerBName: highest.playerB 
      ? `${highest.playerB.firstName} ${highest.playerB.lastName}` 
      : highest.teamB?.name,
    scoreA: highest.scoreA,
    scoreB: highest.scoreB,
    total: maxTotal
  };
}

/**
 * Determine MVP (player with most dominant wins)
 */
async function determineMVP(tournament: TournamentWithRelations): Promise<string | undefined> {
  // MVP is the champion for now
  const champion = tournament.results.find((r) => r.rank === 1);
  return champion?.userId;
}

/**
 * Determine top scorer (player with highest total points scored)
 */
async function determineTopScorer(tournament: TournamentWithRelations): Promise<string | undefined> {
  const scores: Map<string, number> = new Map();

  for (const match of tournament.matches || []) {
    if (match.playerAId && match.scoreA) {
      scores.set(match.playerAId, (scores.get(match.playerAId) || 0) + match.scoreA);
    }
    if (match.playerBId && match.scoreB) {
      scores.set(match.playerBId, (scores.get(match.playerBId) || 0) + match.scoreB);
    }
  }

  let topScorer: string | undefined;
  let maxScore = 0;

  for (const [playerId, score] of scores) {
    if (score > maxScore) {
      maxScore = score;
      topScorer = playerId;
    }
  }

  return topScorer;
}

// ============================================
// RECAP RETRIEVAL
// ============================================

/**
 * Get tournament recap
 */
interface TournamentRecapRecord {
  id: string;
  tournamentId: string;
  sport: string;
  title: string;
  summary: string;
  highlights: string;
  totalMatches: number;
  totalUpsets: number;
  longestMatch: string | null;
  highestScore: string | null;
  mvpPlayerId: string | null;
  topScorerId: string | null;
  standings: string;
  isAutoGenerated: boolean;
  generatedAt: Date;
  isPublic: boolean;
  publishedAt: Date | null;
  createdAt: Date;
  tournament: {
    name: string;
    sport: string;
    startDate: Date | null;
    location: string | null;
  };
}

export async function getTournamentRecap(tournamentId: string): Promise<{
  exists: boolean;
  recap?: TournamentRecapRecord;
  parsed?: {
    highlights: string[];
    standings: StandingEntry[];
    longestMatch: LongestMatchInfo | null;
    highestScore: HighestScoreInfo | null;
  };
}> {
  const recap = await db.tournamentRecap.findUnique({
    where: { tournamentId },
    include: {
      tournament: {
        select: {
          name: true,
          sport: true,
          startDate: true,
          location: true
        }
      }
    }
  });

  if (!recap) {
    return { exists: false };
  }

  return {
    exists: true,
    recap,
    parsed: {
      highlights: JSON.parse(recap.highlights || '[]'),
      standings: JSON.parse(recap.standings || '[]'),
      longestMatch: recap.longestMatch ? JSON.parse(recap.longestMatch) : null,
      highestScore: recap.highestScore ? JSON.parse(recap.highestScore) : null
    }
  };
}

/**
 * Get recent tournament recaps
 */
export async function getRecentRecaps(
  sport: SportType,
  limit: number = 10
): Promise<TournamentRecapRecord[]> {
  return db.tournamentRecap.findMany({
    where: {
      sport,
      isPublic: true,
      publishedAt: { not: null }
    },
    include: {
      tournament: {
        select: {
          name: true,
          location: true,
          scope: true
        }
      }
    },
    orderBy: { createdAt: 'desc' },
    take: limit
  });
}

// ============================================
// HELPERS
// ============================================

async function logRecapAction(
  tournamentId: string,
  action: CompletionAction,
  details: Record<string, any>
): Promise<void> {
  const tournament = await db.tournament.findUnique({
    where: { id: tournamentId },
    select: { sport: true }
  });

  if (!tournament) return;

  await db.tournamentCompletionLog.create({
    data: {
      tournamentId,
      sport: tournament.sport,
      action,
      status: 'SUCCESS',
      details: JSON.stringify(details),
      actorId: null,
      actorRole: 'SYSTEM',
      executedAt: new Date()
    }
  });
}

// ============================================
// EXPORTS
// ============================================

export const TournamentRecapService = {
  generate: generateTournamentRecap,
  get: getTournamentRecap,
  getRecent: getRecentRecaps
};
